version: '3'
services:
    database:
        image: "mysql:latest"
        ports:
            - "3306:3306"
        env_file:
            - mysql_env
        volumes:
            - ./data/mysql/:/var/lib/mysql
    backend:
        ports:
            - "5001:5000"
        build:
            context: .
            dockerfile: docker/Dockerfile-backend
        env_file:
            - flask_env
        depends_on:
          - database
    auth:
        ports:
            - "5002:5000"
        build:
            context: .
            dockerfile: docker/Dockerfile-auth
        env_file:
            - flask_env
        depends_on:
          - database
    frontend:
        ports:
            - "5000:5000"
        build:
            context: .
            dockerfile: docker/Dockerfile-frontend
        env_file:
            - flask_env
