FROM alpine:latest

RUN apk add --update python3

COPY frontend/requirements.txt /tmp/

RUN pip3 install -r /tmp/requirements.txt

WORKDIR /opt/app

COPY frontend /opt/app

COPY items/images app/assets/items

CMD python3 run.py
