FROM alpine:latest

RUN apk add --update python3 python3-dev gcc musl-dev libffi-dev openssl-dev bash

COPY auth /opt/app
COPY users.yml /opt/app

WORKDIR /opt/app

RUN pip3 install -r requirements.txt

RUN chmod +x entrypoint.sh

CMD ./entrypoint.sh
